# https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure

name: Az CLI Login using OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  az-login:
    runs-on: ubuntu-latest
    environment: azure
    steps:
      - name: Az CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
